services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bbc-mcp:latest
    container_name: bbc-mcp-app
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./etc/bbc-mcp-docker.yaml:/app/etc/bbc-mcp.yaml:ro
      - /root/code/tools/:/app/tools
    environment:
      BBC_MCP_CONFIG: /app/etc/bbc-mcp.yaml
      BBC_MCP_KEY: "bspYWis07Q7E1YXlxZOX4Pdal08uNaHPps52Ydeo"
